In [1]:
# Introduction to Numpy -----> 
# Numpy is an open source library that is used for scientific calculations . 

### Why Numpy is better than List ? 
# (1). List hetrogenous data type and Numpy homogenous data type .
# (2). List take more memory as compare to Numpy . 
# (3). List take more time execution as compare to Numpy . 

In [3]:
# !pip install numpy 

In [5]:
import numpy as np 

In [7]:
a = [1,34,54]
type(a)

list

In [9]:
b = np.array(a)
b

array([ 1, 34, 54])

In [11]:
type(b)

numpy.ndarray

In [13]:
a =[]
size = int(input("enter size:"))
for i in range(size):
    val = int(input("enter number:"))
    a.append(val)
b = np.array(a)
b

enter size: 4
enter number: 5
enter number: 6
enter number: 7
enter number: 8


array([5, 6, 7, 8])

In [15]:
type(b)

numpy.ndarray

In [19]:
a = [[1,2,3,0] , [4,5,6,7] , [3,5,7,8]]
b = np.array(a)
b

array([[1, 2, 3, 0],
       [4, 5, 6, 7],
       [3, 5, 7, 8]])

In [21]:
print("Total Shape = " , b.shape)  ###shape = n(rows) , n(columns) 

Total Shape =  (3, 4)


In [23]:
print("Total Elements = " , b.size)  ### size = n(rows) * n(columns) 

Total Elements =  12


In [25]:
print("Total Dimension = " , b.ndim)  ### ndim stands for n_dimension ---> 2 (x,y)

Total Dimension =  2


In [27]:
# Pre-defined functions in Numpy 

In [29]:
# (1). zeros() ----> It will return an array in which all the values will be 0 in 
# either one-dimensional or multi-dimensional . 

In [51]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [53]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
print("Total Shape =", a.shape)
print("Total Elements =", a.size)

Total Shape = (3,)
Total Elements = 3


In [57]:
print("Total Shape =", b.shape)
print("Total Elements =", b.size)

Total Shape = (3, 3)
Total Elements = 9
