In [3]:
import numpy as np

In [5]:
a = [[1,2,3] , [4,5,6] , [7,8,9]]
b= np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Functions 

In [9]:
# (1). zeros() ----> 
a = np.zeros(4) 
a

array([0., 0., 0., 0.])

In [11]:
# (2). ones() ---> It will create an array in which all the values are 1 . 
a = np.ones(4) 
a

array([1., 1., 1., 1.])

In [13]:
# (3). eye() ----> It will create an array in which digonal positional 
# elements will be 1 and rest all are 0 . 

In [15]:
a = np.eye(3) 
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# (4). diag() ----> Using this method , we can create an array in which we can
# customize our digonal positional elements . 

In [19]:
a = np.diag([1,45,67,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 67,  0],
       [ 0,  0,  0, 90]])

## # (5). Random Module 

In [22]:
# (a). Randint() ----> It will generate random numbers in a given range. 
# syntax: np.random.randint(min_value , max_value , total_numbers)

In [24]:
a = np.random.randint(1,10,3)
a

array([1, 3, 2])

In [26]:
# (b). Rand() ----> It will generate random numbers in range 0-1. 

In [28]:
a = np.random.rand(3,3) 
a

array([[0.91519404, 0.13416123, 0.4359678 ],
       [0.04146579, 0.2453761 , 0.21667852],
       [0.53378543, 0.23409353, 0.8494414 ]])

In [30]:
# (c). seed() ----> It will fix our random generated data . 

In [32]:
np.random.seed(30) 
a = np.random.randint(1,10,3)
a

array([6, 6, 5])

In [34]:
# (6). view vs copy ------> 
# view means modification in original dataset . 
# copy means modification in duplicate data . 

In [36]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a[2:5]
b[:] = 0 
b

array([0, 0, 0])

In [38]:
a

array([1, 2, 0, 0, 0, 6, 7, 8, 9])

In [40]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a[2:5].copy() 
b[:] = 0 
b

array([0, 0, 0])

In [42]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])