In [1]:
import numpy as np

# Reshaping the array

In [4]:
# n(rows) * n(columns) = n(total_elements)

# total_elements = 15

# 1*15 , 15*1
# 5*3 , 3*5

In [6]:
a = np.arange(1,13,1)

In [8]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [12]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
a.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

## Operations on array

In [19]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [21]:
a**2

array([ 1,  4,  9, 16])

In [23]:
a*3

array([ 3,  6,  9, 12])

In [43]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [45]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [47]:
a+b

array([[ 6,  8],
       [10, 12]])

In [49]:
a-b

array([[-4, -4],
       [-4, -4]])

In [51]:
a*b

array([[ 5, 12],
       [21, 32]])

In [53]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [55]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a = a.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
np.sum(a)   ## total sum

45

In [61]:
np.sum(a, axis =0)  ## colomn wise sum

array([12, 15, 18])

In [63]:
np.sum(a, axis =1)  ## row wise sum

array([ 6, 15, 24])

## Unique()

In [66]:
# it will return unique elements of array and its indexing and total occurance.

In [68]:
a = np.array([1,2,2,2,2,2,2,2,2,3,1,4,5])
np.unique(a, return_index=True , return_counts=True)

(array([1, 2, 3, 4, 5]),
 array([ 0,  1,  9, 11, 12], dtype=int64),
 array([2, 8, 1, 1, 1], dtype=int64))

## linespace()

In [71]:
# it will return an array in which gap of values will be equal.
# syntax ---> np.linespace(min_num , max_num , total_num)

In [73]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

## Hsatck() and Vstack()

In [76]:
# hstack ---> it will give horizontally.
#  vstack ---> it will give vertically.


In [78]:
a = ([1,2,3,4])
b = ([5,6,7,8])
c = ([9,10,11,12])

In [80]:
np.hstack([a,b,c])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
np.vstack([a,b,c])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])