In [1]:
# numpy --> numpy is an open - source library that is used scitific calculations.


# Why numpy is better than list?

In [5]:
# 1) Numpy is homogenous data type and list is heterogenous datatype.
# 2) numpy take less memory while list take more memory.
# 3) numpy take less execution time while list take more time.
# 4) numpy has more funcationality as compare to list.


In [11]:
import numpy as np

In [9]:
a = [1,45,78,90]
type(a)

list

In [15]:
b= np.array(a)
b

array([ 1, 45, 78, 90])

In [17]:
type(b)

numpy.ndarray

In [35]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# how can we check shape,size , dimension of an array?


In [26]:
print("total rows and columns",b.shape)  ## shape = n(rows), n(columns)
print("total elements",b.size)   ## size = n(rows)*n(columns)
print("total dimension:",b.ndim)  # ndim stands for n-dimensional

total rows and columns (3, 3)
total elements 9
total dimension: 2


# how can we create a user-defined array?

In [31]:
a = []
size = int(input("enter size:"))
for i in range(size):
    val = int(input("enter item:"))
    a.append(val)

# print(a)
b = np.array(a)
b

enter size: 3
enter item: 12
enter item: 46
enter item: 78


array([12, 46, 78])

# Functions in numpy

In [42]:
# 1) Zeros() --> it will create an array in which all the values are zero either 1-d or multi-d.

In [44]:
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [48]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
# 2) ones() --. it will create an array in which all the values are 1 in either 1-d or mult-d.

In [52]:
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [62]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
# 3) eye() --> it will create an array in which digonal positional elements will be 1 and rest all are 0.

In [64]:
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [66]:
# 4) --> diag() --> it will create an array in which we can customize our diag positional elements.

In [68]:
a = np.array([1,34,67,89])
a

array([ 1, 34, 67, 89])

In [70]:
a = np.diag([1,34,67,89])
a

array([[ 1,  0,  0,  0],
       [ 0, 34,  0,  0],
       [ 0,  0, 67,  0],
       [ 0,  0,  0, 89]])

In [72]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr[1, 1, 0])

7


In [76]:
# 5) Random module

# 1) randint --> it will create random number in a given range.
# syntax --> np.random.randint(min_value , max_value , total_numbers)

In [78]:
a = np.random.randint(1,10,3)
a

array([1, 8, 2])

In [80]:
# 2) rand() --> it will create an array in which all the values will be from range 0 to 1.

In [82]:
a = np.random.rand(4)
a

array([0.03, 0.11, 0.52, 0.06])

In [84]:
# 3) seed()  ---> it will fix our random generated data.

In [88]:
np.random.seed(40)
a = np.random.randint(1,10,3)
a

array([7, 8, 6])

# View vs Copy

In [91]:
# view means modification in original dta.
# copy means modification in duplicate data that will not reflect origianl data.

In [93]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [95]:
b = a[2:5]
b[:] = 0
b

array([0, 0, 0])

In [97]:
a

array([1, 2, 0, 0, 0, 6, 7, 8])

In [99]:
a = np.array([1,2,3,4,5,6,7,8])
b = a[2:5].copy()
b[:] = 0
b

array([0, 0, 0])

In [101]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

# Reshaping the array

In [104]:
# n(rows) * n(columns) = n(total_elements)

In [106]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [108]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [110]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [112]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [114]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225])

In [116]:
a**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000, 1331,
       1728, 2197, 2744, 3375], dtype=int32)

In [118]:
# total_elements = 15

# 1*15 , 15*1
# 5*3 , 3*5

In [120]:
a.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [122]:
a.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [124]:
a.reshape(5,5)

ValueError: cannot reshape array of size 15 into shape (5,5)

In [157]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [159]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [161]:
a+b

array([[ 6,  8],
       [10, 12]])

In [163]:
a-b

array([[-4, -4],
       [-4, -4]])

In [165]:
a.dot(b)  ## for matrix multiplication

array([[19, 22],
       [43, 50]])

In [167]:
a/b

array([[0.2 , 0.33],
       [0.43, 0.5 ]])

# unique ()

In [147]:
# it will return 3 arrays.
#  1) arr --> unique elements of array.
# 2) return_index = true ---> indexing of unique element
# 3) return_count = true ---> occurance or frequency of unique elements.

In [155]:
a = np.array([1,2,1,1,1,1,3,2,3,3,3,3,4])
np.unique(a, return_index=True , return_counts=True)


(array([1, 2, 3, 4]),
 array([ 0,  1,  6, 12], dtype=int64),
 array([5, 2, 5, 1], dtype=int64))

# linespace()

In [170]:
# it will return an array in which gap of values will be equal.
# syntax ---> np.linespace(min_num , max_num , total_num)

In [178]:
a = np.linspace(1,10,3)
a

array([ 1. ,  5.5, 10. ])

# Hsatck() and Vstack()

In [181]:
# hstack ---> it will give horizontally.
#  vstack ---> it will give vertically.


In [13]:
a = ([1,2,3,4])
b = ([5,6,7,8])
c = ([9,10,11,12])

In [15]:
np.hstack([a,b,c])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
np.vstack([a,b,c])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])